config/routes.rb
Quizler::Application.routes.draw do

  resources :highscores

  

  root to: 'dashboard#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  get 'quizzes/browse', to: 'quizzes#browse', as: 'quizzes_browse'
  resources :quizzes
  resources :questions

  resources :friends, controller: 'friendships', only: [:index, :create] do
    collection do
      get 'search'
      get 'friendship_requests'
      post 'accept_friendship'
    end
  end

  get 'one_player_game_flow/ready'
  get 'one_player_game_flow/question_option'
  get 'one_player_game_flow/finale'
  get 'one_player_game_flow/score'

  get 'dashboard' => 'dashboard#fetch_questions'

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_user!, :only => :browse

  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.where(author: current_user).paginate(:page => params[:page], :per_page => 30)
  end

  def browse
    @quizzes = Quiz.paginate(:page => params[:page], :per_page => 30)
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
    @author_username = @quiz.author.username
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
    @quiz.author = current_user
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Quiz was successfully created.' }
        format.json { render action: 'show', status: :created, location: @quiz }
      else
        format.html { render action: 'new' }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
      if @quiz.author != current_user
        flash[:alert] = 'You\'re not the author of this quiz and not allowed to access it.'
        redirect_to quizzes_browse_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:title, :description, :author_id, :date)
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
  def cache_key_for_quiz_table(page)
    ("quizzes/#{Quiz.maximum(:updated_at).to_s}/#{page}")
  end

  def cache_key_for_my_quiz_table(current_user, page)
    sql = "SELECT MAX(updated_at) AS max_result FROM quizzes WHERE author_id = #{current_user.id}"
    max_updated_at_result = Quiz.connection.execute(sql)
    updated_at = max_updated_at_result.first['max_result']
    ("quizzes/#{current_user.id}/#{updated_at}/#{page}")
  end
end

app/views/quizzes/_form.html.erb
<%= form_for(@quiz) do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% @quiz.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field hidden">
    <%= f.label :author_id %><br>
    <%= f.text_field :author_id, :readonly => true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzes/browse.html.erb
<% content_for :header do %>
    <h1>Listing quizzes</h1>
<% end %>

<table class="table text-left">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Author</th>
      <th>Created at</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= quiz.title %></td>
        <td><%= quiz.description %></td>
        <td><%= quiz.author.username %></td>
        <td><%= quiz.created_at %></td>
        <% if current_user == quiz.author %>
            <td><%= link_to 'Show', quiz %></td>
        <% else %>
            <td></td>
        <% end %>
        <td><%= link_to 'Play',  one_player_game_flow_ready_path(:quiz_id => quiz)%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Main View', root_path() %>

app/views/quizzes/edit.html.erb
<% content_for :header do %>
    <h1>Editing quiz</h1>
<% end %>

<%= render 'form' %>
<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<% content_for :header do %>
    <h1>Listing quizzes</h1>
<% end %>

<table class="table text-left">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Author</th>
      <th>Created at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= quiz.title %></td>
        <td><%= quiz.description %></td>
        <td><%= quiz.author.username %></td>
        <td><%= quiz.created_at %></td>
        <td><%= link_to 'Show', quiz %></td>
        <td><%= link_to 'Edit', edit_quiz_path(quiz) %></td>
        <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quiz', new_quiz_path(@quiz) %> | <%= link_to 'Main View', root_path() %>

app/views/quizzes/new.html.erb
<% content_for :header do %>
    <h1>New quiz</h1>
<% end %>

<%= render 'form' %>
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/show.html.erb
<% content_for :header do %>
    <h1>Quiz info</h1>
<% end %>

<p>
  <strong>Title:</strong>
  <%= @quiz.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @quiz.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= @author_username %>
</p>

<p>
  <strong>Date:</strong>
  <%= @quiz.created_at %>
</p>

<br>

<table class="table text-left">
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer1</th>
      <th>Answer2</th>
      <th>Answer3</th>
      <th>Answer4</th>
      <th>Correct_answer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @quiz.questions.each do |question| %>
      <tr>
          <td><%= question.question %></td>
          <td><%= question.answer1 %></td>
          <td><%= question.answer2 %></td>
          <td><%= question.answer3 %></td>
          <td><%= question.answer4 %></td>
          <td><%= question.correct_answer %></td>
          <td><%= link_to 'Show', question %></td>
          <td><%= link_to 'Edit', edit_question_path(question) %></td>
          <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add question', new_question_path(:quiz_id => @quiz.id)  %> |
<%= link_to 'Edit', edit_quiz_path(@quiz) %> |
<%= link_to 'Back', quizzes_path %>