config/routes.rb
Quizler::Application.routes.draw do

  resources :highscores

  

  root to: 'dashboard#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  get 'quizzes/browse', to: 'quizzes#browse', as: 'quizzes_browse'
  resources :quizzes
  resources :questions

  resources :friends, controller: 'friendships', only: [:index, :create] do
    collection do
      get 'search'
      get 'friendship_requests'
      post 'accept_friendship'
    end
  end

  get 'one_player_game_flow/ready'
  get 'one_player_game_flow/question_option'
  get 'one_player_game_flow/finale'
  get 'one_player_game_flow/score'

  get 'dashboard' => 'dashboard#fetch_questions'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_before_filter :authenticate_user!, :only => :index

  def index

  end

end

app/views/dashboard/index.html.erb
<% content_for :header do %>
    <h1>Quizzle Time!</h1>
<% end %>

<%= form_tag(one_player_game_flow_ready_path, :method => "get", id: "quiz-id-form") do %>
    <br>
    <%= label_tag('Join quiz by ID') %>
    <br>
    <%= text_field_tag :quiz_id, nil, placeholder: 'Enter ID' %>
    <button type="submit">Find</button>

<% end %>

 <br>
    <%= link_to 'Browse Quizzes', quizzes_browse_path %>
    <br>
<% if user_signed_in? %>
    <%= link_to 'My Quizzes', quizzes_path %>
    <br>
    <%= link_to 'Find friends', search_friends_path %>
    <br>
    <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'js-dashboard-logout-link' %>

<% else %>
    <%= link_to 'Sign up', new_user_registration_path %>
    <br>
    <%= link_to 'Sign in', new_user_session_path, class: 'js-dashboard-login-link' %>
<% end %>