config/routes.rb
Quizler::Application.routes.draw do

  resources :highscores

  

  root to: 'dashboard#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  get 'quizzes/browse', to: 'quizzes#browse', as: 'quizzes_browse'
  resources :quizzes
  resources :questions

  resources :friends, controller: 'friendships', only: [:index, :create] do
    collection do
      get 'search'
      get 'friendship_requests'
      post 'accept_friendship'
    end
  end

  get 'one_player_game_flow/ready'
  get 'one_player_game_flow/question_option'
  get 'one_player_game_flow/finale'
  get 'one_player_game_flow/score'

  get 'dashboard' => 'dashboard#fetch_questions'

end

app/controllers/one_player_game_flow_controller.rb
class OnePlayerGameFlowController < ApplicationController
	skip_before_filter :authenticate_user!
  include CurrentQuiz


  def ready
    begin
      @quiz = Quiz.find(params[:quiz_id])
      set_quiz(@quiz)
      @question_count = Question.count(conditions: "quiz_id = #{@quiz.id}")
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url, :flash => { :alert => "The quiz does not exist" }
    end
  end

  def question_option
  	@quiz_id = current_quiz_id
    @current_quiz_title = current_quiz_title
    @questions = get_questions
    @current_question = get_next_question(@questions)
    @correct_answer = @current_question.correct_answer

  end

  def score
    @questions = get_questions
    @current_question = current_question(@questions)

    @correct_answer = @current_question.correct_answer
    @chosen_answer = params[:format]

    @finished = false
    if (get_question_index+1) >= @questions.size
      @finished = true
    end

    @correct_answer_points = 0
    if @correct_answer.to_i == @chosen_answer.to_i
      @correct_answer_points = 10
      increment_score(@correct_answer_points)
      increment_correct_answers_count
    end

    @correct_answer_text = @current_question.answer1
    if (@correct_answer.to_i == 2)
      @correct_answer_text = @current_question.answer2
    elsif (@correct_answer.to_i == 3)
      @correct_answer_text = @current_question.answer3
    elsif (@correct_answer.to_i == 4)
      @correct_answer_text = @current_question.answer4
    end

    @total_score = get_total_score

  end

  def finale
    begin
      @total_correct_answers_count = get_correct_answers_count
      @questions_count = get_questions.count
      @total_score = get_total_score
      if user_signed_in?
        cell = Highscore.new(user_id: current_user.id, quiz_id: current_quiz_id, score: @total_score)
        cell.save!
      else
        flash.now[:alert] = "Results not recorded, you're not logged in!"
      end
    rescue
      flash.now[:alert] = "Results not recorded, you've already taken this quiz!"
    end
    @highscore = Highscore.where(["quiz_id = ?", current_quiz_id]).order("score DESC")
  end


end

app/helpers/one_player_game_flow_helper.rb
module OnePlayerGameFlowHelper

  def cache_key_for_current_question(question)
    "one_player_game_flow/current_question/#{question.id}/#{question.updated_at}"
  end
end

app/views/one_player_game_flow/finale.erb
<% content_for :header do %>
    <h1> YEAH </h1>
<% end %>

<h3> You got <%= @total_correct_answers_count%> correct answers of <%= @questions_count%> </h3>
<%= button_to "Main Menu", root_path, :class => "button", :method => :get %>

<table class="table text-left">
  <thead>
  <tr>
    <th>Rank</th>
    <th>User</th>
    <th>Score</th>
  </tr>
  </thead>

  <tbody>
  <% @highscore.each do |hs| %>
      <tr>
        <td><%= 1 %></td>
        <td><%= hs.user_id %></td>
        <td><%= hs.score %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/one_player_game_flow/question_option.erb
<% content_for :header do %>
    <h1><%= @current_quiz_title %></h1>
<% end %>

<h3><%= @current_question.question %></h3>
<br>

<%= button_to @current_question.answer1, one_player_game_flow_score_path(1), :class => "button", :method => :get %>

<%= button_to @current_question.answer2, one_player_game_flow_score_path(2), :id => 2, :class => "button", :method => :get %>
<br>
<% if @current_question.answer3 != nil %>
    <%= button_to @current_question.answer3, one_player_game_flow_score_path(3), :id => 3,  :class => "button", :method => :get %>
<%end%>
<% if @current_question.answer4 != nil %>
    <%= button_to @current_question.answer4, one_player_game_flow_score_path(4), :id => 4, :class => "button", :method => :get %>
<%end%>

app/views/one_player_game_flow/ready.erb
<% content_for :header do %>
    <h1>Ready to Quizzle?</h1>
<% end %>

<h2><%=@current_quiz.title%></h2>
<p><%=@current_quiz.description%>
	<br>
	Number of questions:
	<%=@question_count%>
</p>

<%= button_to "Yeah", one_player_game_flow_question_option_path, :class => "button", :method => :get %>
<%= button_to "No, take me back!", root_path, :class => "button", :method => :get %>

app/views/one_player_game_flow/score.erb
<% content_for :header do %>
    <h1>Score:</h1>
<% end %>

<h3>This round: <%= @correct_answer_points %></h3>
<h3>Total: <%= @total_score %></h3>

<h3>Correct answer was: <%= @correct_answer_text %> </h3>

<% if @finished %>
    <%= button_to "See leaderboard!", one_player_game_flow_finale_path, :class => "button", :method => :get %>
<% else %>
    <%= button_to "Next", one_player_game_flow_question_option_path, :class => "button", :method => :get %>
<% end %>