config/routes.rb
Quizler::Application.routes.draw do

  resources :highscores

  

  root to: 'dashboard#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  get 'quizzes/browse', to: 'quizzes#browse', as: 'quizzes_browse'
  resources :quizzes
  resources :questions

  resources :friends, controller: 'friendships', only: [:index, :create] do
    collection do
      get 'search'
      get 'friendship_requests'
      post 'accept_friendship'
    end
  end

  get 'one_player_game_flow/ready'
  get 'one_player_game_flow/question_option'
  get 'one_player_game_flow/finale'
  get 'one_player_game_flow/score'

  get 'dashboard' => 'dashboard#fetch_questions'

end

app/views/layouts/_flash_messages.html.erb
<% if flash[:notice] || flash[:alert] || flash[:warning] %>
    <div class="alert <%= flash[:notice] ? 'alert-success' : '' %> <%= flash[:alert] ? 'alert-danger' : '' %> <%= flash[:warning] ? 'alert-warning' : '' %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span></button>
        <% if flash[:notice] %>
          <i class="fa fa-check u-m-mg-right"></i><%= flash[:notice] %>
        <% elsif flash[:alert] %>
          <i class="fa fa-exclamation u-m-mg-right"></i><%= flash[:alert] %>
        <% elsif flash[:warning] %>
          <i class="fa fa-exclamation-triangle u-m-mg-right"></i><%= flash[:warning] %>
        <% end %>
    </div >
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <%= link_to 'Quizler', root_path, class: 'navbar-brand' %>

    <ul class="nav navbar-nav navbar-right">

      <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle js-nav-friends-dropdown-btn" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-users"></i>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Find Friends', search_friends_path %></li>
              <li><%= link_to 'Friend Requests', friendship_requests_friends_path, class: 'js-nav-friends-friend-requests-link' %></li>
              <li><%= link_to 'My Friends', friends_path %></li>
            </ul>
          </li>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
      <% else %>
          <li><%= link_to 'Log in', new_user_session_path %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Quizler</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
    <%= render '/layouts/nav' %>

    <div class="container">
      <div class= "panel panel-default center-block text-center">

        <% if content_for?(:header) %>
            <div class="panel-heading">
              <%= yield(:header) %>
            </div>
        <% end %>

        <div class="panel-body">
          <%= render '/layouts/flash_messages' %>
          <%= yield %>
        </div>

      </div>
    </div>


    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>